services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coachfoot-php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: coachfoot-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8
    container_name: coachfoot-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coachfoot
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: coachfoot-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - database

volumes:
  db_data: